In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/male_teams.csv')
data.head()

,team_id,team_url,fifa_version,fifa_update,update_as_of,team_name,league_id,league_name,league_level,nationality_id,...,off_corners,off_free_kicks,build_up_play_speed,build_up_play_dribbling,build_up_play_passing,build_up_play_positioning,chance_creation_passing,chance_creation_crossing,chance_creation_shooting,chance_creation_positioning
0,10,/team/10/manchester-city/240002,24,2,2023-09-22,Manchester City,13,Premier League,1.0,14,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,243,/team/243/real-madrid/240002,24,2,2023-09-22,Real Madrid,53,La Liga,1.0,45,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1318,/team/1318/england/240002,24,2,2023-09-22,England,78,Friendly International,NaN,14,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21,/team/21/fc-bayern-munchen/240002,24,2,2023-09-22,FC Bayern München,19,Bundesliga,1.0,21,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,241,/team/241/fc-barcelona/240002,24,2,2023-09-22,FC Barcelona,53,La Liga,1.0,45,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data1 = data.loc[data['fifa_version'] == 24]
data1.head()

,team_id,team_url,fifa_version,fifa_update,update_as_of,team_name,league_id,league_name,league_level,nationality_id,...,off_corners,off_free_kicks,build_up_play_speed,build_up_play_dribbling,build_up_play_passing,build_up_play_positioning,chance_creation_passing,chance_creation_crossing,chance_creation_shooting,chance_creation_positioning
0,10,/team/10/manchester-city/240002,24,2,2023-09-22,Manchester City,13,Premier League,1.0,14,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,243,/team/243/real-madrid/240002,24,2,2023-09-22,Real Madrid,53,La Liga,1.0,45,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1318,/team/1318/england/240002,24,2,2023-09-22,England,78,Friendly International,NaN,14,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21,/team/21/fc-bayern-munchen/240002,24,2,2023-09-22,FC Bayern München,19,Bundesliga,1.0,21,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,241,/team/241/fc-barcelona/240002,24,2,2023-09-22,FC Barcelona,53,La Liga,1.0,45,...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data1.to_csv('data/male_teams_update.csv')